site_name: Plight Of Women
theme:
  name: material
  feature:
   -navigation.tabs
   -navigation.sections
   -toc.integrate
   -navigation.top
   -search.suggest
   -search.highlight
   -content.tabs.link
   -content.code.annotation
   -content.code.copy
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: llime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
        generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
  - pymdownx.mark
  - attr_list